FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY . .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install setuptools cassandra-driver minio flask-socketio eventlet

EXPOSE 5001

CMD ["python", "resources/web/predict_flask.py"]
