apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: flight-prediction
type: Opaque
stringData:
  access-key: minioadmin
  secret-key: minioadmin
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-airflow-credentials
  namespace: flight-prediction
type: Opaque
stringData:
  username: airflow
  password: airflow
  database: airflow
  connection: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-mlflow-credentials
  namespace: flight-prediction
type: Opaque
stringData:
  username: mlflow
  password: mlflow
  database: mlflow
  connection: postgresql://mlflow:mlflow@postgres-mlflow/mlflow
